import Footer from '@/components/molecules/Footer';
import NavList from '@/components/molecules/NavList';
import Navbar from '@/components/organism/Navbar';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Contact from 'src/layout/Contact';
import Experience from 'src/layout/Experience';
import Hero from 'src/layout/Hero';
import Layout from 'src/layout/Layout';
import Projects from 'src/layout/Projects';
import Work from 'src/layout/Work';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div>
      <div className={styles.wrapper}>
        <div className={styles.bg} />
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Layout>
          <>
            <Hero />
            <Work />
            <Experience />
            <Projects />
            <Contact />
            <NavList isFooter={true} />
          </>
        </Layout>
      </div>
      <Footer />
    </div>
  );
};

export default Home;
